# Generated by Django 4.1.6 on 2023-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0002_remove_servey_content_servey_first_answer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servey",
            name="branch",
            field=models.CharField(default=1, max_length=4),
            preserve_default=False,
        ),
    ]
