# Generated by Django 4.1.6 on 2023-02-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0004_servey_first_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="servey",
            name="second_count",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
