# Generated by Django 4.1.6 on 2023-02-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("servey", "0007_alter_servey_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servey",
            name="title",
            field=models.TextField(max_length=100),
        ),
    ]
