# Generated by Django 4.1.6 on 2023-02-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("count_day", "0002_count_day_time_alter_count_day_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="count_day",
            old_name="Time",
            new_name="time",
        ),
    ]
