# Generated by Django 4.1.6 on 2023-02-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("count_day", "0003_rename_time_count_day_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="count_day",
            name="day",
            field=models.DateField(blank=True, null=True),
        ),
    ]
